### ISSUE TITLE
ERROR: unable to download video data: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by rojter-tech** [rojter-tech/pluradl.py#13]
This error now shows up on my testing environments. While [403](https://github.com/rojter-tech/pluradl.py/issues/12) is not ... Pluralsight is probably tweaking something.

```bash
[download] Sleeping 60.82 seconds...
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/home/dreuter/Github/pluradl.py/plura_dl/PluraDL.py", line 1926, in process_info
    success = dl(filename, info_dict)
  File "/home/dreuter/Github/pluradl.py/plura_dl/PluraDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/home/dreuter/Github/pluradl.py/plura_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/home/dreuter/Github/pluradl.py/plura_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/home/dreuter/Github/pluradl.py/plura_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/home/dreuter/Github/pluradl.py/plura_dl/PluraDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by rojter-tech** [comment]
Workarounds implemented to master and the [latest release](https://github.com/rojter-tech/pluradl.py/releases/latest).

**Comment by 7wOv6ySCjo** [comment]
Yes. Now it works in Windows 8.

But have an question about these new settings:
```
SLEEP_INTERVAL = 40     # minimum sleep time        #                                 #
SLEEP_OFFSET   = 120    # adding random sleep time  #  Change this at your own risk.  #
```
this new settings are safely to avoid blocks?
I changed the SLEEP_INTERVAL to 300 because I'm actually downloading 24 hours a day.
Do you think 300 is a good value? or 40 is fine for 24 hours?

**Comment by 7wOv6ySCjo** [comment]
Can reply please?

**Comment by rojter-tech** [comment]
@7wOv6ySCjo
This new the sleep offset makes this more undetectable. There is too much risk for Pluralsight to automaticly block this kind of request pattern. Rate is now 1.7 minutes from the 2.7 minutes it was before.

**Comment by rojter-tech** [comment]
@7wOv6ySCjo 

Btw, the action of having a 24/7 download streak is the biggest risk of using this implementation. A setting of minium sleep time of 300 and no offset will in general comlete around 5 courses per day spread over the whole 24 hour interval, but the request pattern is completly predictable.
Minimum sleep time 40 and sleep offset of 120 will in general complete 15 courses per day spread over the 24 hour interval, but the request pattern is unpredictable.

The unpredictability will have a higher chance to not get detected by their security system, but If 15 courses per day compared to 5 will cause any security lamps to blink red I am not so sure.
