### ISSUE TITLE
Only first video being downloaded

### ISSUE THREAD

**Issue by voodoologic** [rojter-tech/pluradl.py#14]
Everything works smooth for the first video.  After the timeout, it attempts to get the second video and it fails with the following error.
```
ERROR: No video formats found; please report this issue on https://github.com/rojter-tech/pluradl.py/issues . Make sure you are using the latest version; see  https://github.com/rojter-tech/pluradl.py/wiki  on how to update. Be sure to call plura-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/oldbones/Hack/pluradl.py/plura_dl/PluraDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/home/oldbones/Hack/pluradl.py/plura_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/oldbones/Hack/pluradl.py/plura_dl/extractor/pluralsight.py", line 421, in _real_extract
    self._sort_formats(formats)
  File "/home/oldbones/Hack/pluradl.py/plura_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
plura_dl.utils.ExtractorError: No video formats found; please report this issue on https://github.com/rojter-tech/pluradl.py/issues . Make sure you are using the latest version; see  https://github.com/rojter-tech/pluradl.py/wiki  on how to update. Be sure to call plura-dl with the --verbose flag and include its complete output.
```

**Comment by rojter-tech** [comment]
Did you follow the recommendation to manually visit the course html page via the specified link? If so, what information did you get from there?

**Comment by voodoologic** [comment]
Did a little digging and discovered that my trial version doesn't give me access to those videos.  Closing

**Comment by voodoologic** [comment]
I got booted from the platform after about 48 hours of straight downloading.  I now get a 403 error.
