### ISSUE TITLE
Error while downloading

### ISSUE THREAD

**Issue by hot9cups** [rojter-tech/pluradl.py#28]
I get the following three errors during my download, and they occur on video #1 of the 34 videos itself. 
```
ERROR: unable to download video data: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 1319, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 966, in send
    self.connect()
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1414, in connect
    super().connect()
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 728, in create_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hot9c\plural\pluradl.py\plura_dl\PluraDL.py", line 1926, in process_info
    success = dl(filename, info_dict)
  File "C:\Users\hot9c\plural\pluradl.py\plura_dl\PluraDL.py", line 1865, in dl
    return fd.download(name, info)
  File "C:\Users\hot9c\plural\pluradl.py\plura_dl\downloader\common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "C:\Users\hot9c\plural\pluradl.py\plura_dl\downloader\http.py", line 341, in real_download
    establish_connection()
  File "C:\Users\hot9c\plural\pluradl.py\plura_dl\downloader\http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "C:\Users\hot9c\plural\pluradl.py\plura_dl\PluraDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\hot9c\plural\pluradl.py\plura_dl\utils.py", line 2728, in https_open
    req, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 1321, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
```

After this, the prompt terminates with the following message:

```
Something went wrong.
The download request for 'powershell-toolmaking-fundamentals' was forced to terminate.
Double check that https://app.pluralsight.com/library/courses/powershell-toolmaking-fundamentals
exists or that your subscription is valid for accessing its content.

Moving content to C:\Users\hot9c\plural\pluradl.py\courses\_failed\powershell-toolmaking-fundamentals
Moving to next course playlist

Sleeping for 60 seconds ...

(base) C:\Users\hot9c\plural\pluradl.py>
```

Edit: I re-executed it, this time the error occured after video 6
How do I download the whole thing without the error ever occurring?

**Comment by rojter-tech** [comment]
@hot9cups Okey, so you were able to successfully download the first 5 videos before you experience an URLError? Is this specific behaviour reproducable, I mean when you retry downloading the videos in that particular playlist, is it still so that the first 5 videos is being sucessfully downloaded and then the URLError is casted at the 6th one?

**Comment by hot9cups** [comment]
@rojter-tech erm no, if I execute it again, it stops at the 13th video. So I think it's pretty random, but it does stop.
