### ISSUE TITLE
Error downloading JSON metadata

### ISSUE THREAD

**Issue by NickB1** [rojter-tech/pluradl.py#46]
Hi,

Managed to download a course, the second course gave the following error:
Unable to download JSON metadata: HTTP Error 403: Forbidden

Also tried it on other courses but got the same issue.

Full log:
(downloading 114 of them)
[download] Downloading video 1 of 114
[pluralsight] Downloading login page
[pluralsight] Logging in
[pluralsight] be2f2941-118c-4a30-ab60-6eab6b788c19-0: Downloading JSON metadata
[pluralsight] be2f2941-118c-4a30-ab60-6eab6b788c19-0: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] be2f2941-118c-4a30-ab60-6eab6b788c19-0: Downloading mp4-high-widescreen viewclip JSON
[pluralsight] be2f2941-118c-4a30-ab60-6eab6b788c19-0: Waiting for 3 seconds to avoid throttling
[pluralsight] be2f2941-118c-4a30-ab60-6eab6b788c19-0: Downloading captions JSON
[debug] Invoking downloader on
[download] Sleeping 105.09 seconds...
[download]   0.0% of 4.63MiB at  3.32KiB/s ETA 23:46
[download]   0.1% of 4.63MiB at  9.97KiB/s ETA 07:55
[download]   0.1% of 4.63MiB at 22.11KiB/s ETA 03:34
[download]   0.3% of 4.63MiB at 46.41KiB/s ETA 01:41
[download]   0.7% of 4.63MiB at 95.92KiB/s ETA 00:49
[download]   1.3% of 4.63MiB at 194.93KiB/s ETA 00:23
[download]   2.7% of 4.63MiB at 358.30KiB/s ETA 00:12
[download]   5.4% of 4.63MiB at 412.87KiB/s ETA 00:10
[download]  10.8% of 4.63MiB at 483.48KiB/s ETA 00:08
[download]  21.6% of 4.63MiB at 481.98KiB/s ETA 00:07
[download]  31.7% of 4.63MiB at 477.52KiB/s ETA 00:06
[download]  41.6% of 4.63MiB at 484.80KiB/s ETA 00:05
[download]  52.4% of 4.63MiB at 484.85KiB/s ETA 00:04
[download]  62.6% of 4.63MiB at 485.79KiB/s ETA 00:03
[download]  73.0% of 4.63MiB at 486.22KiB/s ETA 00:02
[download]  83.3% of 4.63MiB at 483.12KiB/s ETA 00:01
[download]  93.0% of 4.63MiB at 487.18KiB/s ETA 00:00
[download] 100.0% of 4.63MiB at 486.78KiB/s ETA 00:00
[download] 100% of 4.63MiB in 00:09
[download] Downloading video 2 of 114
Unable to download JSON metadata: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://github.com/rojter-tech/pluradl.py/issues . Make sure you are using the latest version; see  https://github.com/rojter-tech/pluradl.py/wiki  on how to update. Be sure to call plura-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "E:\Courses\pluradl.py\plura_dl\PluraDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "E:\Courses\pluradl.py\plura_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "E:\Courses\pluradl.py\plura_dl\extractor\pluralsight.py", line 421, in _real_extract
    self._sort_formats(formats)
  File "E:\Courses\pluradl.py\plura_dl\extractor\common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
plura_dl.utils.ExtractorError: No video formats found; please report this issue on https://github.com/rojter-tech/pluradl.py/issues . Make sure you are using the latest version; see  https://github.com/rojter-tech/pluradl.py/wiki  on how to update. Be sure to call plura-dl with the --verbose flag and include its complete output.

**Comment by NickB1** [comment]
Same as https://github.com/rojter-tech/pluradl.py/issues/40
