### ISSUE TITLE
Unable to download JSON metadata: HTTP Error 403: Forbidden (not banned)

### ISSUE THREAD

**Issue by Bigemul** [rojter-tech/pluradl.py#63]
Hi everyone

I didn't have any problem for days and a couple of hours ago I got that:

```
Downloading video indicies from 6 up to and including 24
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] plura-dl version 1.0.0b4
[debug] Python version 3.8.2 (CPython) - macOS-10.15.4-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {}
[pluralsight:course] coursename: Downloading JSON metadata
[download] Downloading playlist: Understanding 3D in Photoshop
[pluralsight:course] playlist Understanding 3D in Photoshop: Collected 24 video ids (downloading 19 of them)
[download] Downloading video 1 of 19
[pluralsight] Downloading login page
[pluralsight] Logging in
[pluralsight] coursename-m2-1: Downloading JSON metadata
[pluralsight] coursename-m2-1: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] coursename-m2-1: Downloading mp4-high-widescreen viewclip JSON
Unable to download JSON metadata: HTTP Error 403: Forbidden
[pluralsight] coursename: Waiting for 2 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://github.com/rojter-tech/pluradl.py/issues . Make sure you are using the latest version; see  https://github.com/rojter-tech/pluradl.py/wiki  on how to update. Be sure to call plura-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/username/Desktop/Pluralsight/pluradl.py-master/plura_dl/PluraDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/Users/username/Desktop/Pluralsight/pluradl.py-master/plura_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/Users/username/Desktop/Pluralsight/pluradl.py-master/plura_dl/extractor/pluralsight.py", line 421, in _real_extract
    self._sort_formats(formats)
  File "/Users/username/Desktop/Pluralsight/pluradl.py-master/plura_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
plura_dl.utils.ExtractorError: No video formats found; please report this issue on https://github.com/rojter-tech/pluradl.py/issues . Make sure you are using the latest version; see  https://github.com/rojter-tech/pluradl.py/wiki  on how to update. Be sure to call plura-dl with the --verbose flag and include its complete output.

Something went wrong.
The download request for 'coursename' was forced to terminate.
Double check that https://app.pluralsight.com/library/courses/coursename exists or that your subscription is valid for accessing its content.

Moving content to /Users/username/Desktop/Pluralsight/pluradl.py-master/courses/_failed/coursename
Moving to next course playlist

Sleeping for 80 seconds ...
^CTraceback (most recent call last):
  File "pluradl.py", line 303, in <module>
    main()
  File "pluradl.py", line 299, in main
    download_courses(courses)
  File "pluradl.py", line 262, in download_courses
    time.sleep(SLEEP_PLAYLIST)
KeyboardInterrupt
```

Did Pluralsight change anything, making the program not able to download anything?
I tried on another computer and got the same problem. I didn't have any problem on this one either.

I guess Pluralsight didn't change anything. This error occurred a couple of hours ago and now it works.

**Comment by fortunewalla** [comment]
having exact same issue. Tried to wait for more 12 hours and tried but still got the same error message. Not banned (can play course in browser)

```
Downloading video indicies from 15 up to and including 35
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] plura-dl version 1.0.0b4
[debug] Git HEAD: b1adc2a
[debug] Python version 3.7.6 (CPython) - Linux-4.18.0-147.8.1.el8_1.x86_64-with-centos-8.1.1911-Core
[debug] exe versions: none
[debug] Proxy map: {}

Unable to download JSON metadata: HTTP Error 403: Forbidden
[pluralsight] 07c2c9dd-8bd6-48d6-bc60-c631b5000666-0: Waiting for 3 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://github.com/rojter-tech/pluradl.py/issues . Make sure you are using the latest version; see  https://github.com/rojter-tech/pluradl.py/wiki  on how to update. Be sure to call plura-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/pluraloffline/pluradl.py/plura_dl/PluraDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/pluraloffline/pluradl.py/plura_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/pluraloffline/pluradl.py/plura_dl/extractor/pluralsight.py", line 421, in _real_extract
    self._sort_formats(formats)
  File "/pluraloffline/pluradl.py/plura_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
plura_dl.utils.ExtractorError: No video formats found; please report this issue on https://github.com/rojter-tech/pluradl.py/issues . Make sure you are using the latest version; see  https://github.com/rojter-tech/pluradl.py/wiki  on how to update. Be sure to call plura-dl with the --verbose flag and include its complete output.

Something went wrong.
The download request for 'pluralsight-access-guides' was forced to terminate.
Double check that https://app.pluralsight.com/library/courses/leading-emotional-intelligence
exists or that your subscription is valid for accessing its content.

Moving content to /pluraloffline/pluradl.py/courses/_failed/leading-emotional-intelligence
Traceback (most recent call last):
  File "/pluraloffline/pluradl.py/plura_dl/PluraDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/pluraloffline/pluradl.py/plura_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/pluraloffline/pluradl.py/plura_dl/extractor/pluralsight.py", line 421, in _real_extract
    self._sort_formats(formats)
  File "/pluraloffline/pluradl.py/plura_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
plura_dl.utils.ExtractorError: No video formats found; please report this issue on https://github.com/rojter-tech/pluradl.py/issues . Make sure you are using the latest version; see  https://github.com/rojter-tech/pluradl.py/wiki  on how to update. Be sure to call plura-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pluradl.py", line 96, in invoke_download
    pdl.download([course_url])
  File "/pluraloffline/pluradl.py/plura_dl/PluraDL.py", line 2019, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/pluraloffline/pluradl.py/plura_dl/PluraDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/pluraloffline/pluradl.py/plura_dl/PluraDL.py", line 1008, in process_ie_result
    extra_info=extra)
  File "/pluraloffline/pluradl.py/plura_dl/PluraDL.py", line 875, in process_ie_result
    extra_info=extra_info, download=False, process=False)
  File "/pluraloffline/pluradl.py/plura_dl/PluraDL.py", line 820, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/pluraloffline/pluradl.py/plura_dl/PluraDL.py", line 625, in report_error
    self.trouble(error_message, tb)
  File "/pluraloffline/pluradl.py/plura_dl/PluraDL.py", line 595, in trouble
    raise DownloadError(message, exc_info)
plura_dl.utils.DownloadError: ERROR: No video formats found; please report this issue on https://github.com/rojter-tech/pluradl.py/issues . Make sure you are using the latest version; see  https://github.com/rojter-tech/pluradl.py/wiki  on how to update. Be sure to call plura-dl with the --verbose flag and include its complete output.
```
