### ISSUE TITLE
ImportError: No module named pathlib

### ISSUE THREAD

**Issue by ann-bereza** [rojter-tech/pluradl.py#65]
Hi! I am unable to use the plurald.py, because I constantly get this error:

 
python pluradl.py
 Traceback (most recent call last):
   File "pluradl.py", line 5, in <module>
     from plura_dl.scrapeutils import extract_user_credentials, Logger
   File "/Users/annhavelia/Documents/pluralsight/pluradl.py/plura_dl/scrapeutils.py", line 5, in <module>
     from pathlib import Path
 ImportError: No module named pathlib

Pls, help

**Comment by ann-bereza** [comment]
Found a solution
